repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: end-of-file-fixer
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: trailing-whitespace
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: requirements-txt-fixer
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: mixed-line-ending
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
  # lint the dockerfiles
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
  - repo: https://github.com/codespell-project/codespell.git
    rev: "v2.4.1" # Use the sha / tag you want to point at
    hooks:
      - id: codespell
        types: [text]
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|.+\.json|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other|rootfs/webapp/adsb.py|acarshub-typescript/src/interfaces.ts)
