---
name: Deploy Trixie Test Images

on:
  # Enable manual running of action if necessary
  workflow_dispatch:
    inputs:
      reason:
        required: true
        description: "Reason for running this workflow"
      disable_upstream_triggers:
        required: false
        type: boolean
        description: "Rebuild the base images but don't trigger downstream builds"
        default: false
  # disable deploy on push, only deployed manually as this build will trigger
  # tons of other rebuilds
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WORKFLOW_AUTH_TOKEN: ${{ secrets.GH_PAT_MIKENYE }}
  WORKFLOW_REASON: "triggered via deploy_ghcr.yml in sdr-enthusiasts/docker-baseimage"

jobs:
  hadolint:
    name: Run hadolint against docker files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Pull hadolint/hadolint:latest Image
        run: docker pull hadolint/hadolint:latest
      - name: Run hadolint against Dockerfiles
        run: docker run --rm -i -v "$PWD":/workdir --workdir /workdir --entrypoint hadolint hadolint/hadolint --ignore DL3003 --ignore DL3006 --ignore DL3010 --ignore DL4001 --ignore DL3007 --ignore DL3008 --ignore SC2068 --ignore DL3007 --ignore SC1091 --ignore DL3013 --ignore DL3010 $(find . -type f -iname "Dockerfile*")

  # Basefile
  deploy_ghcr_base:
    name: Base
    needs: [hadolint]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-base
      docker_build_file: trixie/Dockerfile.base
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # Next steps are all of the deployments that depend on the base image
  deploy_ghcr_mlat_client:
    needs: [deploy_ghcr_base]
    name: Mlat Client
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-mlatclient
      build_baseimage_test: true
      build_baseimage_url: :base/:trixie-base
      docker_build_file: trixie/Dockerfile.mlatclient
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  deploy_ghcr_planefence_base:
    name: Planefence
    needs: [deploy_ghcr_base]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-planefence_base
      build_baseimage_test: true
      build_baseimage_url: :base/:trixie-base
      docker_build_file: trixie/Dockerfile.planefence_base
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # deployments that only rely on rtlsdr

  deploy_ghcr_soapy_full:
    name: Soapy Full
    needs: [deploy_ghcr_base]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-soapy-full
      build_baseimage_test: true
      build_baseimage_url: :base/:trixie-base
      docker_build_file: trixie/Dockerfile.soapy-full
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # deployments that rely on rtlsdr AND mlatclient

  deploy_ghcr_wreadsb:
    name: Wreadsb
    needs: [deploy_ghcr_base, deploy_ghcr_mlat_client]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-wreadsb
      build_baseimage_test: true
      build_baseimage_url: :mlatclient/:trixie-mlatclient/g;s/:base/:trixie-base
      docker_build_file: trixie/Dockerfile.wreadsb
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # deployments that rely on just soapy-full

  deploy_ghcr_acars-decoder-soapy:
    name: ACARS Decoder Soapy
    needs: [deploy_ghcr_wreadsb]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-acars-decoder-soapy
      build_baseimage_test: true
      build_baseimage_url: :soapy-full/:trixie-soapy-full
      docker_build_file: trixie/Dockerfile.acars-decoder-soapy
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # deployments that rely on just wreadsb

  deploy_dump978-full:
    name: Dump978 Full
    needs: [deploy_ghcr_wreadsb]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      build_with_tmpfs: false
      build_latest: true
      docker_latest_tag: trixie-dump978-full
      build_baseimage_test: true
      build_baseimage_url: :wreadsb/:trixie-wreadsb
      docker_build_file: trixie/Dockerfile.dump978-full
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  trigger_build_base:
    name: Trigger deploy of base image
    needs: [deploy_ghcr_base]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.disable_upstream_triggers != 'true' }}
    steps:
      - name: acarshub
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-acarshub deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: beast-splitter
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-beast-splitter deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: flightradar24
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-flightradar24 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: adsbhub
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-adsbhub deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: opensky
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-opensky-network deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: planefinder
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-planefinder deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: acars_router
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/acars_router deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: airspy
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/airspy_adsb deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: reversewebproxy
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-reversewebproxy deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: radar1090
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-radar1090 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: flightairmap
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-flightairmap deploy_trixie.yml -f reason="$WORKFLOW_REASON"

      # # moved from rtlsdr to base image
      # - name: shipfeeder
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-shipfeeder deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: aprs-tracker
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-aprs-tracker deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: vesselalert
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-vesselalert deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: acars-oxide
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/acars-oxide deploy_trixie.yml -f reason="$WORKFLOW_REASON"

  trigger_build_acars_soapy:
    name: Trigger deploy of acars decoder soapy images
    needs: [deploy_ghcr_acars-decoder-soapy]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.disable_upstream_triggers != 'true' }}
    steps:
      - name: acarsdec
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-acarsdec deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: dumpvdl2
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-dumpvdl2 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: dumpvdl2dec
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-vdlm2dec deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: dumphfdl
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-dumphfdl deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: hfdlobserver
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-hfdlobserver deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: rtlsdrairband
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-rtlsdrairband deploy_trixie.yml -f reason="$WORKFLOW_REASON"

  # trigger_build_planefence:
  #   name: Trigger deploy of sdr-enthusiasts/docker-planefence
  #   needs: [deploy_ghcr_planefence_base]
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.inputs.disable_upstream_triggers != 'true' }}
  #   steps:
  #     - name: Planefence
  #       continue-on-error: true
  #       run: |
  #         echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
  #         gh workflow run --ref main --repo sdr-enthusiasts/docker-planefence deploy_trixie.yml -f reason="$WORKFLOW_REASON"

  trigger_build_wreadsb:
    name: Trigger deploy of wreadsb/mlatclient images
    needs: [deploy_ghcr_wreadsb, deploy_ghcr_mlat_client]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.disable_upstream_triggers != 'true' }}
    steps:
      # - name: airnav
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-airnavradar deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: radarvirtuel
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-radarvirtuel deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: tar1090
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-tar1090 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      # - name: sdrplay_beast1090
      #   continue-on-error: true
      #   run: |
      #     echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
      #     gh workflow run --ref main --repo sdr-enthusiasts/docker-sdrplay-beast1090 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
      - name: sdrmap
        continue-on-error: true
        run: |
          echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
          gh workflow run --ref main --repo sdr-enthusiasts/docker-sdrmap deploy_trixie.yml -f reason="$WORKFLOW_REASON"

  # trigger_build_dump978:
  #   name: Trigger deploy of sdr-enthusiasts/docker-dump978
  #   needs: [deploy_dump978-full]
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.inputs.disable_upstream_triggers != 'true' }}
  #   steps:
  #     - name: dump978
  #       continue-on-error: true
  #       run: |
  #         echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
  #         gh workflow run --ref main --repo sdr-enthusiasts/docker-dump978 deploy_trixie.yml -f reason="$WORKFLOW_REASON"
  #     - name: piaware
  #       continue-on-error: true
  #       run: |
  #         echo "$WORKFLOW_AUTH_TOKEN" | gh auth login --with-token
  #         gh workflow run --ref main --repo sdr-enthusiasts/docker-piaware deploy_trixie.yml -f reason="$WORKFLOW_REASON"
